// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDp2aj_5ie7D7JU_uSpYZQihq3ooygbbo',
    appId: '1:424651675886:web:06e4210f00bd384fe9fbff',
    messagingSenderId: '424651675886',
    projectId: 'taskmanager-39dfc',
    authDomain: 'taskmanager-39dfc.firebaseapp.com',
    storageBucket: 'taskmanager-39dfc.firebasestorage.app',
    measurementId: 'G-HR6YP9MMLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABUiSC3TdWbHDsk2_zLp6qZG0NndRW-cA',
    appId: '1:424651675886:android:6fd100221d6b6992e9fbff',
    messagingSenderId: '424651675886',
    projectId: 'taskmanager-39dfc',
    storageBucket: 'taskmanager-39dfc.firebasestorage.app',
  );
}
